// Google urun taksonomisinden (taxonomy-with-ids.tr-TR.txt, surum 2021-09-21)
// magazamizla ilgili kategoriler - admin kategori sayfasindaki secim listesi ve
// Merchant feed'deki google_product_category (bkz. app/feed/google.xml).
// Kimlikler resmi listeden dogrulandi; yeni secenek eklerken oradan alin.
export const DEFAULT_GOOGLE_CATEGORY_ID = 166; // Kıyafet ve Aksesuarlar

export const GOOGLE_CATEGORIES: { id: number; label: string }[] = [
  { id: 166, label: "Kıyafet ve Aksesuarlar (genel)" },
  { id: 1604, label: "Giyim Eşyaları (genel)" },
  { id: 212, label: "Giyim > Gömlekler ve Üstlükler (tişört, bluz, kazak, sweatshirt)" },
  { id: 204, label: "Giyim > Pantolonlar (kot, eşofman altı, tayt)" },
  { id: 207, label: "Giyim > Şortlar" },
  { id: 1581, label: "Giyim > Etekler" },
  { id: 2271, label: "Giyim > Elbiseler" },
  { id: 5250, label: "Giyim > Tulumlar" },
  { id: 7313, label: "Giyim > Takımlar" },
  { id: 1594, label: "Giyim > Takım Elbiseler" },
  { id: 5322, label: "Giyim > Spor Kıyafetler" },
  { id: 203, label: "Giyim > Dış Giyim (genel)" },
  { id: 5598, label: "Giyim > Dış Giyim > Montlar ve Ceketler (blazer, trençkot)" },
  { id: 1831, label: "Giyim > Dış Giyim > Yelekler" },
  { id: 211, label: "Giyim > Mayolar" },
  { id: 213, label: "Giyim > İç Giyim ve Çoraplar" },
  { id: 209, label: "Giyim > İç Giyim ve Çoraplar > Çoraplar" },
  { id: 208, label: "Giyim > Yatak ve Ev Kıyafetleri (pijama, gecelik)" },
  { id: 187, label: "Ayakkabılar" },
  { id: 3032, label: "El Çantaları" },
  { id: 167, label: "Kıyafet Aksesuarları (genel)" },
  { id: 169, label: "Aksesuar > Kemerler" },
  { id: 173, label: "Aksesuar > Şapkalar" },
  { id: 177, label: "Aksesuar > Atkı ve Şallar" },
  { id: 171, label: "Aksesuar > Saç Aksesuarları" },
  { id: 188, label: "Mücevherler (takı, bijuteri)" },
  { id: 479, label: "Kozmetik > Parfüm ve Kolonya" }
];

// Mevcut kategoriler icin ilk atama (scripts/google-kategori-ata.ts) - sonrasi
// admin kategori sayfasindan degistirilir.
export const INITIAL_GOOGLE_CATEGORY_BY_SLUG: Record<string, number> = {
  tisort: 212,
  bluz: 212,
  gomlek: 212,
  "polo-yaka": 212,
  sweatshirt: 212,
  kazak: 212,
  "kazak-suveter": 212,
  hirka: 212,
  atlet: 212,
  pantolon: 204,
  "kot-pantolon": 204,
  "esofman-alti": 204,
  "eşofman-altı": 204,
  tayt: 204,
  sort: 207,
  "sort-bermuda": 207,
  etek: 1581,
  elbise: 2271,
  "abiye-davetiye": 2271,
  tulum: 5250,
  esofman: 5322,
  "dis-giyim": 203,
  "dış-giyim": 203,
  ceket: 5598,
  blazer: 5598,
  "blazer-ceket": 5598,
  "mont-kaban": 5598,
  trenckot: 5598,
  yelek: 1831,
  "mayo-bikini": 211,
  "ic-giyim": 213,
  boxer: 213,
  corap: 209,
  "pijama-gecelik": 208,
  ayakkabi: 187,
  canta: 3032,
  aksesuar: 167,
  kemer: 169,
  "sapka-bere": 173,
  "sal-atki": 177,
  "sac-aksesuarlari": 171,
  "taki-bijuteri": 188,
  parfum: 479,
  "parfüm": 479
};
